# Generated by Django 2.2.12 on 2020-08-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='logo',
            field=models.ImageField(null=True, upload_to='logo/siteinfo'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='logo_footer',
            field=models.ImageField(null=True, upload_to='logo_footer/siteinfo'),
        ),
    ]
