# Generated by Django 2.2.12 on 2020-08-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200830_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='logo_slogan',
            field=models.ImageField(upload_to='imageSlogan/siteinfo'),
        ),
    ]
