# Generated by Django 2.2.12 on 2020-08-31 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200831_1239'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lieu',
            new_name='Lieu_contact',
        ),
        migrations.AlterModelOptions(
            name='lieu_contact',
            options={'verbose_name': 'Lieu_contact', 'verbose_name_plural': 'Lieu_contacts'},
        ),
    ]
