# Generated by Django 2.2.12 on 2020-08-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200831_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieu_contact',
            name='adresse',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
