# Generated by Django 2.2.12 on 2020-08-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_lieu_contact_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='need_help',
            name='adresse',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='need_help',
            name='proposition',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
