# Generated by Django 2.2.12 on 2020-08-31 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200831_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='need_help',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='need_help',
            name='proposition',
        ),
    ]
