# Generated by Django 2.2.12 on 2020-08-31 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200831_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='lien',
        ),
    ]
