# Generated by Django 2.2.12 on 2020-08-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_tag_lien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='lien',
        ),
        migrations.AddField(
            model_name='faq',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
