# Generated by Django 2.2.12 on 2020-08-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaussid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cause',
            name='gaol',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cause',
            name='raised',
            field=models.CharField(max_length=50),
        ),
    ]
